/* Remaining content types (BRD 7.2): travel ideas, events, stories, organisations, news and the site configuration.
   Sample entries for the prototype; CIDEAL replaces them from the CMS. Only public fields are held here. */
window.CONTENT = (() => {
  const A = f => 'ASSETS/' + encodeURI(f);
  const img = (base, ws, alt) => ({ src: A(base + '-' + ws[Math.min(1, ws.length - 1)] + '.webp'), srcset: ws.map(w => A(base + '-' + w + '.webp') + ' ' + w + 'w').join(', '), alt });
  const std = (base, big, alt) => img(base, [480, 960, big], alt);
  const asw = (n, alt) => img('asw-' + n, [480, 960, 1280], alt);

  /* ---- travel ideas: curated by CIDEAL from published destinations and experiences; the order is CMS data ---- */
  const travelIdeas = [
    { slug: 'luxor-in-two-days', city: 'luxor', p: 'culture', dur: 'يومان', n: 'الأقصر في يومين', s: 'البر الشرقي يومًا والبر الغربي يومًا، مع مساء على النيل.', d: 'مسار يوزّع المعابد الكبرى على الضفتين دون عجلة: الكرنك والأقصر في اليوم الأول، ثم وادي الملوك وحتشبسوت وتمثالا ممنون في الثاني، وبينهما فلوكة عند الغروب وعشاء في مطعم محلي.', img: std('92ceaae3-c7f0-4e2b-a86c-ab490f6e9ff2', 1448, 'أعمدة معبد الكرنك'), stops: [['d', 'karnak-temple'], ['d', 'luxor-temple'], ['e', 'nile-felucca'], ['e', 'local-restaurants'], ['d', 'valley-of-the-kings'], ['d', 'hatshepsut-temple'], ['d', 'colossi-of-memnon']] },
    { slug: 'west-bank-slow-day', city: 'luxor', p: 'gems', dur: 'يوم واحد', n: 'يوم هادئ في البر الغربي', s: 'حقول وقرى ومعابد بإيقاع أبطأ، بعيدًا عن الحافلات.', d: 'يبدأ اليوم مع أول ضوء فوق البر الغربي، ثم مسار بالدراجة بين الحقول والقرى، وغداء صعيدي، وينتهي عند تمثالي ممنون قبل الغروب.', img: std('البر الغربي', 1672, 'البر الغربي للأقصر عند الغروب'), stops: [['e', 'hot-air-balloon'], ['e', 'west-bank-exploring'], ['e', 'traditional-food'], ['d', 'colossi-of-memnon']] },
    { slug: 'nubian-aswan', city: 'aswan', p: 'culture', dur: 'يومان', n: 'أسوان النوبية', s: 'جزر وقرى ملوّنة وضيافة نوبية على ضفة النيل.', d: 'يومان بين جزيرة إلفنتين ومتحف النوبة وقرية غرب سهيل، مع ورشة فضة وعشاء منزلي نوبي، والمبيت في بيت ضيافة نوبي.', img: asw('nubian2', 'زقاق بجدران زرقاء في قرية نوبية'), stops: [['d', 'elephantine-island'], ['d', 'nubian-museum'], ['e', 'nubian-village-experience'], ['e', 'nubian-silver-workshop'], ['e', 'home-cooked-nubian'], ['e', 'nubian-guesthouses']] },
    { slug: 'aswan-by-water', city: 'aswan', p: 'gems', dur: 'يوم واحد', n: 'أسوان من الماء', s: 'فيلة والجزر والفلوكة في يوم واحد على النيل.', d: 'مركب إلى معبد فيلة صباحًا، ثم جزيرة النباتات، وفلوكة بين الصخور قبل الغروب تنتهي عند مطعم على النيل.', img: asw('nile3', 'فلوكة بين صخور أسوان'), stops: [['d', 'philae-temple'], ['d', 'kitchener-island'], ['e', 'felucca-nile-tour'], ['e', 'nile-restaurants-aswan']] },
    { slug: 'crafts-trail', city: 'luxor', p: 'crafts', dur: 'نصف يوم', n: 'مسار الحرف في الأقصر', s: 'ورش جلد وإكسسوارات يديرها رواد أعمال محليون.', d: 'زيارة ورشة الحرفجية لمشاهدة قطع الجلد تُقطع وتُخاط، ثم إكسسوارات زينب، وينتهي المسار بشاي على الكورنيش.', img: std('Fatma Boghdady', 1448, 'فاطمة البغدادي في ورشتها'), stops: [['e', 'el-herfagya-leather'], ['e', 'zainab-accessories'], ['e', 'corniche-cafes']] },
  ];

  /* ---- events for entrepreneurs and organisations (BRD: trainings, forums, gatherings) ---- */
  const events = [
    { slug: 'helmak-cohort-3-open-day', n: 'يوم مفتوح: الدفعة الثالثة من برنامج حلمك', s: 'تعرّف على مسار الحضانة وشروط التقديم والتقِ بخريجي الدفعات السابقة.', d: 'يوم مفتوح يعرض فيه فريق حلمك مسار الحضانة من التقديم حتى التخرج، ويتحدث خريجو الدفعتين السابقتين عن تجربتهم. يُختتم اليوم بجلسة أسئلة ومقابلات قصيرة للراغبين في التقديم.', start: '2026-10-22T11:00', end: '2026-10-22T15:00', city: 'luxor', loc: 'مركز شباب الأقصر', online: false, aud: 'entrepreneurs', p: 'products', kind: 'لقاء', reg: 'contact.html?subject=general', img: img('ev/helmak-cohort-3-open-day', [480, 960, 1280], 'قاعة تدريب مع مشاركين في ورشة'), imgcr: 'Alhaj Darajaati · CC0' },
    { slug: 'pricing-workshop-aswan', n: 'ورشة تسعير المنتجات اليدوية', s: 'ورشة عملية ليوم واحد مع حرفيي أسوان عن التكلفة والسعر وهامش الربح.', d: 'ورشة تطبيقية يحضر فيها كل مشارك منتجًا من إنتاجه، ويخرج بورقة تكلفة وسعر بيع مقترح. تُقدَّم بالعربية ويقودها مدرّب من برنامج حلمك.', start: '2026-11-05T10:00', end: '2026-11-05T16:00', city: 'aswan', loc: 'البيت النوبي، غرب سهيل', online: false, aud: 'entrepreneurs', p: 'crafts', kind: 'تدريب', reg: 'contact.html?subject=general', img: img('ev/pricing-workshop-aswan', [480, 960, 1280], 'أطباق وسلال مصنوعة يدويًا في سوق'), imgcr: 'ولاء · Public domain' },
    { slug: 'upper-egypt-tourism-forum', n: 'منتدى السياحة المستدامة في صعيد مصر', s: 'رواد أعمال وجهات سياحية وشركاء في يوم للتشبيك وعرض التجارب.', d: 'جلسات قصيرة عن سلاسل القيمة السياحية في الأقصر وأسوان، ومعرض لمنتجات رواد الأعمال، ولقاءات مباشرة بين المشاريع الصغيرة والمنظمين والفنادق.', start: '2026-11-26T09:30', end: '2026-11-26T17:00', city: 'luxor', loc: 'فندق ونتر بالاس', online: false, aud: 'both', p: 'culture', kind: 'منتدى', reg: 'contact.html?subject=press', img: img('ev/upper-egypt-tourism-forum', [480, 960, 1280], 'جمهور في قاعة مؤتمرات'), imgcr: 'U.S. Department of State · Public domain' },
    { slug: 'digital-marketing-webinar', n: 'ويبينار: عرض تجربتك للزوار على الإنترنت', s: 'جلسة عبر الإنترنت عن الصور والنصوص التي تجعل الزائر يحجز.', d: 'ساعة واحدة عبر الإنترنت عن تصوير المنتج والتجربة بالهاتف، وكتابة وصف قصير يُترجم جيدًا، وما الذي يبحث عنه الزائر الأجنبي قبل أن يتواصل.', start: '2026-12-03T18:00', end: '2026-12-03T19:00', city: null, loc: null, online: true, aud: 'entrepreneurs', p: 'products', kind: 'تدريب', reg: 'contact.html?subject=general', img: img('ev/digital-marketing-webinar', [480, 960, 1280], 'سيدة تتابع جلسة عبر الإنترنت على حاسوبها'), imgcr: 'Shixart1985 · CC BY 2.0' },
  ];

  /* ---- success stories: placement flags decide the lead story and the home block (BRD 7.2) ---- */
  const stories = [
    { slug: 'fatma-el-herfagya', n: 'من محل خامات إلى خط تصدير: قصة الحرفجية', person: 'فاطمة البغدادي', ent: 'fatma-boghdady', city: 'luxor', p: 'crafts', cat: 'حرف يدوية', lead: true, home: true, s: 'تسع سنوات من البحث عن وظيفة انتهت بورشة تصدّر حقائب جلدية بنقوش فرعونية.', body: ['بدأت فاطمة البغدادي رحلتها عام 2006 بعد تسع سنوات من البحث عن وظيفة ثابتة دون جدوى، فافتتحت محلًا صغيرًا لبيع خامات الحرف اليدوية في الأقصر.', 'من هناك انتقلت إلى إصلاح الحلي والإكسسوارات، ثم إلى إعادة تدوير الخامات وتحويلها إلى قطع جديدة، وجمعت حولها فريقًا من الحرفيين المتخصصين في التطريز والجلود.', 'عبر برنامج حلمك اكتسبت فاطمة معرفة واسعة في التصميم والتسويق وبناء خطط عمل متينة، وأطلقت مؤخرًا خطًا للتصدير من الحقائب الجلدية بتصاميم فرعونية.'], img: std('Fatma Boghdady', 1448, 'فاطمة البغدادي في ورشتها بالأقصر'), pos: '62% 35%' },
    { slug: 'manal-beit-elnoby', n: 'البيت النوبي: خمسون سيدة وحرفة واحدة', person: 'منال عوض الله', ent: 'manal-awadallah', city: 'aswan', p: 'crafts', cat: 'مهارات وتدريب', lead: false, home: true, s: 'من تعليم الخياطة في 2014 إلى مركز ثقافي يدرّب خمسين سيدة ويحوّل الحرف النوبية إلى دخل.', body: ['بدأت منال عوض الله عام 2014 بتعليم الخياطة للسيدات، ثم توسّعت إلى حرف متعددة حتى أسست "البيت النوبي".', 'يدرّب المركز اليوم خمسين سيدة على التطريز والجلود والطباعة بالشاشة الحريرية، بفريق أساسي من خمس عشرة سيدة وعاملات متناوبات، ويقدّم ورشًا للأطفال.', 'يحقق المركز دخله من الإنتاج بالجملة وتأجير أماكن للبائعين وتجهيز ديكورات الأفراح، وعبر حلمك تعلّمت منال التخطيط الواقعي وإدارة مكان يجمع حرفًا متعددة.'], img: std('Manal Awaga', 1448, 'منال عوض الله في البيت النوبي'), pos: '62% 40%' },
    { slug: 'zainab-accessories', n: 'ورشة في البيت وحلم بمتجر: زينب جمال', person: 'زينب جمال', ent: 'zainab-gamal', city: 'luxor', p: 'products', cat: 'إكسسوارات', lead: false, home: true, s: 'ورشة أدوات واحدة في 2018 فتحت لزينب طريقًا علّمت نفسها فيه حتى صار لها تصاميمها.', body: ['في عام 2018 أنهت زينب جمال ورشة تدريبية عن أساسيات استخدام الأدوات، فأشعلت فيها شغف صناعة الإكسسوارات.', 'علّمت نفسها بالتجربة والبحث على الإنترنت حتى طوّرت تصاميمها الخاصة من ورشة صغيرة في بيتها بالأقصر.', 'ساعدها برنامج حلمك على التخطيط لمشروعها من الصفر: إعداد الميزانية، وتحديد المخاطر، وإدارة الموارد. وتطمح إلى افتتاح متجر خاص والتوسّع خارج الأقصر.'], img: std('Zainab Gamal', 1461, 'زينب جمال تعرض إكسسواراتها اليدوية'), pos: '25% 40%' },
    { slug: 'nubian-silver', n: 'خاتم باسمك: ورشة تفتح أبوابها للزوار', person: 'حرفيو أسوان', ent: 'nubian-silver-workshop', city: 'aswan', p: 'crafts', cat: 'حرف نوبية', lead: false, home: false, s: 'ورشة فضة نوبية حوّلت حرفة قديمة إلى تجربة يصنع فيها الزائر خاتمه بنفسه.', body: ['في محل صائغ نوبي صغير بأسوان، قرر الحرفيون أن يفتحوا ورشتهم للزوار بدل أن يبيعوا لهم فقط.', 'يتعلم الزائر أساسيات تشكيل الفضة ويخرج بخاتم منقوش باسمه بالحروف النوبية، فيما تحافظ الورشة على حرفة كادت تندثر.', 'التجربة اليوم من أكثر ما يُطلب في أسوان، وتدرّ دخلًا ثابتًا على ثلاث أسر من الحرفيين.'], img: asw('silver', 'حرفية نوبية تنقش الفضة في ورشتها'), pos: '50% 40%' },
  ];

  /* ---- organisations: public fields only. Private contact fields never leave the CMS. ---- */
  const ORG_TYPE = { gov: 'جهة حكومية', ngo: 'منظمة أهلية', uni: 'جامعة', private: 'مشغّل قطاع خاص' };
  const VALUE_CHAIN = { stay: 'الإقامة', food: 'الطعام والشراب', crafts: 'إنتاج الحرف اليدوية', guiding: 'الإرشاد والتفسير', transport: 'النقل', tours: 'تنظيم الرحلات' };
  const organisations = [
    { slug: 'luxor-tourism-authority', n: 'هيئة تنشيط السياحة بالأقصر', type: 'gov', city: 'luxor', vc: ['tours', 'guiding'], d: 'الجهة الحكومية المسؤولة عن الترويج السياحي للأقصر وتنسيق الفعاليات مع المحافظة.', ll: [25.6989, 32.6421], contact: 'https://www.egypt.travel' },
    { slug: 'cideal-egypt', n: 'مؤسسة CIDEAL في مصر', type: 'ngo', city: 'luxor', vc: ['crafts', 'tours'], d: 'المنظمة المنفذة لبرنامج تعزيز البدائل الاقتصادية والاجتماعية المستدامة القائمة على السياحة في صعيد مصر.', ll: [25.7045, 32.6400], contact: 'https://www.cideal.org' },
    { slug: 'south-valley-university', n: 'جامعة جنوب الوادي، كلية السياحة والفنادق', type: 'uni', city: 'luxor', vc: ['guiding', 'stay'], d: 'كلية تخرّج مرشدين سياحيين وكوادر فندقية وتشارك في دراسات سلاسل القيمة.', ll: [25.6950, 32.6360], contact: 'https://www.svu.edu.eg' },
    { slug: 'nile-sailing-cooperative', n: 'جمعية مراكب الفلوكة بأسوان', type: 'private', city: 'aswan', vc: ['transport', 'tours'], d: 'تعاونية تضم نوتية الفلوكة في أسوان وتنظّم الجولات النيلية والأسعار الموحدة.', ll: [24.0905, 32.8990], contact: 'contact.html?subject=general' },
    { slug: 'aswan-tourism-directorate', n: 'مديرية السياحة بأسوان', type: 'gov', city: 'aswan', vc: ['tours', 'stay'], d: 'الجهة الحكومية المختصة بتراخيص المنشآت السياحية والتنسيق مع المشغّلين في أسوان.', ll: [24.0880, 32.8975], contact: 'https://www.egypt.travel' },
    { slug: 'nubian-heritage-association', n: 'جمعية التراث النوبي', type: 'ngo', city: 'aswan', vc: ['crafts', 'food'], d: 'جمعية أهلية توثّق الحرف والمطبخ النوبي وتدعم ورش السيدات في غرب سهيل.', ll: [24.0500, 32.8720], contact: 'contact.html?subject=general' },
    { slug: 'winter-palace-hotel', n: 'فندق ونتر بالاس', type: 'private', city: 'luxor', vc: ['stay', 'food'], d: 'فندق تراثي على كورنيش النيل يشارك في معرض منتجات رواد الأعمال ويستضيف منتدى السياحة المستدامة.', ll: [25.6967, 32.6369], contact: 'https://www.sofitel.com' },
    { slug: 'aswan-university', n: 'جامعة أسوان، قسم الإرشاد السياحي', type: 'uni', city: 'aswan', vc: ['guiding'], d: 'يدرّب القسم مرشدين من أبناء أسوان ويتعاون مع البرنامج في تدريب الشباب.', ll: [24.0750, 32.8990], contact: 'https://www.aswu.edu.eg' },
  ];

  /* ---- sector news ---- */
  const news = [
    { slug: 'helmak-third-cohort-call', n: 'فتح باب التقديم للدفعة الثالثة من برنامج حلمك', s: 'يستقبل البرنامج طلبات رواد الأعمال من الأقصر وأسوان حتى نهاية أكتوبر.', date: '2026-10-01', city: null, p: 'products', img: std('Fatma Boghdady', 1448, 'فاطمة البغدادي في ورشتها'), body: ['أعلنت CIDEAL وشركاؤها فتح باب التقديم للدفعة الثالثة من برنامج حلمك لحضانة مشروعات السياحة في صعيد مصر.', 'يستهدف البرنامج الشباب والسيدات أصحاب الأفكار أو المشروعات الصغيرة في الحرف والضيافة والإرشاد والطعام، ويقدّم تدريبًا ومتابعة لمدة ستة أشهر.', 'يُغلق باب التقديم في 31 أكتوبر، ويُعقد يوم مفتوح في الأقصر يوم 22 أكتوبر للتعريف بالبرنامج.'], rel: [['event', 'helmak-cohort-3-open-day']] },
    { slug: 'value-chain-study-published', n: 'نشر دراسة سلاسل القيمة السياحية في الأقصر وأسوان', s: 'الدراسة ترصد ست سلاسل قيمة وتحدد فرص الدخل للمشروعات الصغيرة فيها.', date: '2026-09-18', city: null, p: 'culture', img: std('92ceaae3-c7f0-4e2b-a86c-ab490f6e9ff2', 1448, 'أعمدة معبد الكرنك'), body: ['أصدر البرنامج دراسة سلاسل القيمة السياحية التي رصدت ست سلاسل: الإقامة، الطعام والشراب، إنتاج الحرف اليدوية، الإرشاد والتفسير، النقل، وتنظيم الرحلات.', 'تحدد الدراسة في كل سلسلة أين يمكن للمشروعات الصغيرة والنساء والشباب أن يدخلوا بقيمة مضافة حقيقية، وتقترح تدخلات تدريبية لكل منها.', 'الدراسة متاحة ضمن الموارد لرواد الأعمال والجهات السياحية.'], rel: [['resource', 'business-plan-template']] },
    { slug: 'hidden-gems-aswan', n: 'عشرة كنوز مخفية جديدة على خريطة أسوان', s: 'فريق البرنامج وثّق أماكن وتجارب أقل شهرة في أسوان وأضافها إلى المنصة.', date: '2026-09-05', city: 'aswan', p: 'gems', img: asw('elephantine2', 'جزيرة إلفنتين من النيل'), body: ['ضمن مسار تحديد الكنوز المخفية، وثّق فريق البرنامج مع شباب من أسوان عشرة أماكن وتجارب خارج المسارات المعتادة.', 'من بينها ورش فضة في السوق القديم، وبيوت ضيافة على الجزر، ووجبات منزلية في قرى غرب سهيل.', 'تظهر هذه الكنوز اليوم على خريطة أسوان وفي قوائم الأماكن والتجارب.'], rel: [['destination', 'elephantine-island'], ['experience', 'nubian-silver-workshop']] },
  ];

  /* ---- site configuration (BRD 7.2: one entry edited by an administrator) ---- */
  const site = {
    email: 'info@discoverupperegypt.org',
    subjects: [['general', 'سؤال عام'], ['correction', 'تصحيح في أحد المداخل'], ['listing', 'طلب الإدراج كرائد أعمال'], ['press', 'استفسار صحفي أو شراكة']],
    responseDays: { general: 5, directory: 10, registration: 10, update: 5 },
    retentionMonths: 24,
    about: {
      programme: 'تعزيز البدائل الاقتصادية والاجتماعية المستدامة القائمة على السياحة في صعيد مصر، مع تركيز خاص على النساء والشباب',
      code: 'AECID 2023/ACDE/000XXX',
      funder: 'الوكالة الإسبانية للتعاون الإنمائي الدولي (AECID)',
      partners: [['CIDEAL', 'المنظمة المنفذة'], ['FPSC', 'مؤسسة الترقية الاجتماعية'], ['KEF', 'مؤسسة التعليم والمعرفة'], ['ENROOT', 'شريك التنمية المحلية']],
    },
  };

  const PILLAR_PLACEMENT = { lead: () => stories.find(s => s.lead) || stories[0], home: () => stories.filter(s => s.home) };
  return { travelIdeas, events, stories, organisations, news, site, ORG_TYPE, VALUE_CHAIN, placement: PILLAR_PLACEMENT,
    ideaHref: i => 'travel-idea.html?slug=' + i.slug, eventHref: e => 'event.html?slug=' + e.slug, storyHref: s => 'story.html?slug=' + s.slug, orgHref: o => 'organisation.html?slug=' + o.slug, newsHref: n => 'news-article.html?slug=' + n.slug };
})();
