/* Experiences & products: one dataset, scoped by city. Fields follow the BRD entry model.
   Optional fields are simply absent when unknown and the detail page hides their section:
     dur   duration text            pr    price band 1–4            a     accessibility keys (see listing-shared AC)
     hl    [] highlights            inc   [] what's included        exc   [] what's not included
     it    [{t, d}] itinerary steps imp   [] important information  meet  {t, ll?} meeting point text (+ own coordinates)
     lang  [] language codes        acc   accessibility note        ent   provider card      ll  [lat, lng]
     book  external booking URL     contact contact route (defaults to contact.html) — the platform never checks out or charges. */
window.EXPERIENCES = (() => {
  const A = f => 'ASSETS/' + encodeURI(f);
  const img = (base, ws, alt) => ({ src: A(base + '-' + ws[Math.min(1, ws.length - 1)] + '.webp'), srcset: ws.map(w => A(base + '-' + w + '.webp') + ' ' + w + 'w').join(', '), alt });
  const std = (base, big, alt) => img(base, [480, 960, big], alt);
  const asw = (n, alt) => img('asw-' + n, [480, 960, 1280], alt);
  /* gallery: n photos under ASSETS/gal/<slug>-<i>-<w>.webp (Wikimedia Commons, credited in galcr) */
  const G = (slug, n, alt) => Array.from({ length: n }, (_, i) => img('gal/' + slug + '-' + (i + 1), [480, 960, 1280], alt));
  const CAT = { tour: 'جولة إرشادية', workshop: 'ورشة', food: 'طعام وشراب', stay: 'إقامة', product: 'منتج محلي' };
  const PIL = { gems: 'كنوز مخفية', culture: 'ثقافة وطقوس', food: 'مذاقات', crafts: 'حرف يدوية', folk: 'فلكلور وروحانيات', products: 'منتجات رواد الأعمال' };
  const FATMA = { name: 'فاطمة البغدادي', biz: 'الحرفجية', sum: 'تُبدع فاطمة في تصميم وصناعة منتجات جلدية يدوية مستوحاة من التراث المصري القديم.', img: std('Fatma Boghdady', 1448, 'فاطمة البغدادي في ورشتها بالأقصر'), href: 'entrepreneur.html?slug=fatma-boghdady', pos: '62% 35%' };
  const ZAINAB = { name: 'زينب جمال', biz: 'زينب للإكسسوارات', sum: 'تصنع زينب إكسسوارات يدوية مستوحاة من جمال الطبيعة والتراث المحلي.', img: std('Zainab Gamal', 1461, 'زينب جمال تعرض إكسسواراتها اليدوية'), href: 'entrepreneur.html?slug=zainab-gamal', pos: '25% 40%' };
  const MANAL = { name: 'منال عوض الله', biz: 'البيت النوبي', sum: 'تعمل منال على تدريب السيدات في المجتمع النوبي والحفاظ على الحرف اليدوية النوبية.', img: std('Manal Awaga', 1448, 'منال عوض الله في البيت النوبي'), href: 'entrepreneur.html?slug=manal-awadallah', pos: '62% 40%' };
  const felucca = std('38ee86c3-b80b-4c1b-abcd-37e619a2827f', 1448, 'فلوكة تعبر النيل عند الغروب');
  const evening = std('60ceeb86-ec92-4c29-a148-e06a51d46fd7', 1448, 'أمسية على ضفاف النيل مع موسيقى وشاي');
  const tea = std('11e105f9-71d4-4a46-a890-aa48443d4a92', 1448, 'رجلان صعيديان يتشاركان الشاي والتمر على ضفاف النيل');
  const L = [
    { slug: 'hot-air-balloon', c: 'tour', p: 'gems', n: 'رحلات المناطيد', s: 'تحليق فوق البر الغربي والنيل مع أول ضوء للشروق.', d: 'تنطلق المناطيد قبل الشروق من البر الغربي، فترى الحقول الخضراء والمعابد والجبل من الأعلى بينما تتلوّن السماء تدريجيًا. رحلة هادئة تنتهي بالهبوط قرب القرى، وتُعد من أجمل الطرق لفهم جغرافيا الأقصر بين النيل والصحراء.', dur: 'ساعة تقريبًا', imgs: [std('رحلة المنطاد', 1448, 'مناطيد ملوّنة تحلّق فوق النيل ومعابد الأقصر عند الشروق'), std('البر الغربي', 1672, 'البر الغربي للأقصر عند الغروب')], ll: [25.7135, 32.6185], hl: ['الإقلاع قبل الشروق من البر الغربي', 'مشاهدة الحقول والمعابد والجبل من الأعلى', 'الهبوط قرب القرى مع نهاية الرحلة'], inc: ['رحلة المنطاد نحو ساعة', 'مرافقة طاقم محلي'], gal: G('hot-air-balloon', 5, 'مناطيد تستعد للإقلاع وتحلّق فوق البر الغربي في الأقصر'), galcr: 'Wouter Hagens، Marcosleal · CC BY-SA 3.0' },
    { slug: 'cultural-experiences', c: 'workshop', p: 'culture', n: 'التجارب الثقافية', s: 'شاي وحكايات في جلسة مع أهل الأقصر.', d: 'جلسة على ضفة النيل أو في بيت من بيوت القرية، تُقدَّم فيها ضيافة الصعيد وتُروى حكايات المكان وعاداته. تجربة صغيرة الحجم تقرّبك من الناس أكثر من أي معلم.', dur: 'ساعتان تقريبًا', imgs: [std('التجارب الثقافية', 1536, 'رجل صعيدي يصبّ الشاي لزائرة في جلسة تطل على النيل'), tea], ll: [25.7085, 32.6295], gal: G('cultural-experiences', 3, 'وجوه وجلسات شاي من حياة أهل الصعيد'), galcr: 'Mona Hassan Abo-Abda، Engaashraf96، Mahmoud Hamed ismailia · CC BY-SA 4.0' },
    { slug: 'west-bank-exploring', c: 'tour', p: 'gems', n: 'استكشاف البر الغربي', s: 'مسار بين الحقول والقرى والمعابد عند سفح الجبل.', d: 'جولة بالدراجة أو سيرًا بين حقول القصب والنخيل، تمرّ بقرى البر الغربي وتنتهي عند سفح الجبل حيث المقابر والمعابد. مناسبة لمن يريد إيقاعًا أبطأ بعيدًا عن الحافلات.', dur: 'نصف يوم', imgs: [std('البر الغربي', 1672, 'البر الغربي للأقصر: حقول ونخيل عند سفح الجبل ومعبد حتشبسوت وقت الغروب'), std('place-hatshepsut', 717, 'معبد حتشبسوت ليلًا')], ll: [25.7265, 32.6150], gal: G('west-bank-exploring', 5, 'حقول القصب والجبل والمعابد في البر الغربي'), galcr: 'Marc Ryckaert (MJJR)، anagh، ianpudsey، Kyle Taylor · CC BY 3.0، CC BY-SA 3.0، CC BY 2.0' },
    { slug: 'temple-visits', c: 'tour', p: 'culture', n: 'زيارة المعابد', s: 'جولات مع مرشدين محليين في الكرنك والأقصر.', d: 'جولة إرشادية في معبدي الكرنك والأقصر مع مرشد من أبناء المدينة، يشرح النقوش والطقوس ويربطها بحياة الناس اليوم. الأفضل في الصباح الباكر أو قبل الغروب.', dur: '3 ساعات تقريبًا', imgs: [std('92ceaae3-c7f0-4e2b-a86c-ab490f6e9ff2', 1448, 'مرشد محلي يعرّف الزوار بمعبد الأقصر عند الغروب'), std('place-karnak', 736, 'أعمدة معبد الكرنك'), std('7f49851b-f977-41e4-a9f4-053337fbd944', 1448, 'تماثيل وأعمدة معبد الأقصر')], ll: [25.7188, 32.6573], gal: G('temple-visits', 4, 'أعمدة وبهو الكرنك ومعبد الأقصر'), galcr: 'MusikAnimal، Vyacheslav Argenberg، Gary Todd from Xinzheng, China · CC BY-SA 4.0، CC BY 4.0، CC0' },
    { slug: 'nile-felucca', c: 'tour', p: 'gems', n: 'رحلات نيلية', s: 'جولة بالفلوكة على النيل وقت الغروب.', d: 'إبحار هادئ بالفلوكة الشراعية بين ضفتي الأقصر، تشاهد فيه جزيرة الموز والمعابد من الماء، وينتهي مع الغروب. تناسب الأفراد والعائلات والمجموعات الصغيرة.', dur: 'ساعة إلى ساعتين', imgs: [felucca, std('7d3260b6-e059-456d-afd3-cdbeb1af3126', 1672, 'معبد الأقصر مطلًّا على النيل عند الغروب')], ll: [25.7012, 32.6368], hl: ['إبحار شراعي هادئ بين ضفتي الأقصر', 'جزيرة الموز والمعابد من الماء', 'العودة مع الغروب'], gal: G('nile-felucca', 4, 'فلوكات بأشرعتها البيضاء على نيل الأقصر'), galcr: 'Wouter Hagens · CC BY-SA 3.0' },
    { slug: 'nile-restaurants', c: 'food', p: 'food', n: 'مطاعم على ضفاف النيل', s: 'أطباق مصرية بإطلالة مباشرة على النهر.', d: 'مطاعم على كورنيش النيل تقدّم الأطباق المصرية والصعيدية مع إطلالة على البر الغربي، من الفطور حتى العشاء وقت الغروب.', imgs: [tea, evening], ll: [25.6965, 32.6378], gal: G('nile-restaurants', 4, 'كورنيش الأقصر وإطلالة النيل'), galcr: 'Marc Ryckaert، Vyacheslav Argenberg · CC BY 3.0، CC BY-SA 4.0، CC BY 4.0' },
    { slug: 'local-restaurants', c: 'food', p: 'food', n: 'مطاعم محلية', s: 'مأكولات صعيدية تقليدية في مطاعم يديرها أهل المكان.', d: 'مطاعم صغيرة في أحياء المدينة وقرى البر الغربي، تقدّم الطواجن والخبز الشمسي والأطباق التي يأكلها أهل الأقصر كل يوم.', imgs: [std('food-local-restaurant', 1280, 'مطعم محلي صغير في الأقصر'), std('food-koshari', 1280, 'طبق كشري مصري')], ll: [25.7045, 32.6262], gal: G('local-restaurants', 5, 'أطباق مصرية تقليدية'), galcr: 'Dina Said، Tarboosh، Yosi I، Habib M’henni، Basma · CC BY-SA 4.0، CC0، CC BY 2.5، CC BY-SA 3.0' },
    { slug: 'corniche-cafes', c: 'food', p: 'food', n: 'مقاهي الكورنيش', s: 'جلسات هادئة وموسيقى وشاي على كورنيش النيل.', d: 'مقاهٍ على الكورنيش وفي الأزقة القريبة من معبد الأقصر، للشاي والقهوة والشيشة ومتابعة حركة المراكب على النهر.', imgs: [evening], ll: [25.6938, 32.6362], gal: G('corniche-cafes', 4, 'حدائق وممشى كورنيش النيل في الأقصر'), galcr: 'Marc Ryckaert · CC BY-SA 4.0' },
    { slug: 'traditional-food', c: 'food', p: 'food', n: 'مأكولات تقليدية', s: 'كشري وفول وطعمية وخبز شمسي من قلب المطبخ المصري.', d: 'جولة في الأكلات الشعبية: الفول والطعمية في الصباح، الكشري ظهرًا، والخبز الشمسي من أفران القرى. طريقة بسيطة ورخيصة لتذوّق المدينة.', imgs: [std('food-koshari', 1280, 'طبق كشري مصري بالصلصة والحمص')], ll: [25.7000, 32.6400], gal: G('traditional-food', 4, 'كشري وفول وخبز بلدي من المطبخ المصري'), galcr: 'Furibond Arria Belli، Dina Said، Morios · CC BY-SA 2.0، CC BY-SA 4.0، CC BY-SA 3.0' },
    { slug: 'winter-palace', c: 'stay', p: 'culture', n: 'فندق ونتر بالاس', s: 'فندق تراثي على كورنيش النيل بحدائقه وواجهته التاريخية.', d: 'فندق تاريخي افتُتح مطلع القرن العشرين على كورنيش النيل، بحدائق واسعة وواجهة كلاسيكية، ويقع على خطوات من معبد الأقصر.', imgs: [std('stay-winter-palace', 1280, 'واجهة فندق ونتر بالاس التاريخي في الأقصر')], ll: [25.6967, 32.6369], hl: ['فندق تاريخي افتُتح مطلع القرن العشرين', 'حدائق واسعة وواجهة كلاسيكية على الكورنيش', 'على خطوات من معبد الأقصر'], gal: G('winter-palace', 5, 'فندق ونتر بالاس وحدائقه على كورنيش الأقصر'), galcr: 'Rowan، ianpudsey، Jay Galvin، Bonnie Ann Cain-Wood، VasenkaPhotography · Public domain، CC BY 3.0، CC BY 2.0' },
    { slug: 'steigenberger-nile-palace', c: 'stay', p: 'gems', n: 'شتايجنبرجر نايل بالاس', s: 'فندق على النيل بإطلالة مباشرة على النهر والبر الغربي.', d: 'فندق على ضفة النيل جنوب الكورنيش، بمرسى خاص للمراكب وإطلالة مفتوحة على البر الغربي.', imgs: [std('stay-steigenberger', 1280, 'فندق شتايجنبرجر نايل بالاس ومراكب شراعية أمامه')], ll: [25.6889, 32.6322], gal: G('steigenberger-nile-palace', 5, 'فنادق ومراكب النيل في الأقصر'), galcr: 'Olaf Tausch، Marc Ryckaert، Alyssa Bivins · CC BY 3.0، CC BY-SA 4.0' },
    { slug: 'jolie-ville-kings-island', c: 'stay', p: 'gems', n: 'جولي فيل كينجز آيلاند', s: 'منتجع على جزيرة في النيل بين الحدائق والنخيل.', d: 'منتجع يشغل جزيرة كاملة في النيل جنوب المدينة، بحدائق ومسابح على الماء ومراكب تنقل النزلاء إلى الضفة.', imgs: [std('stay-jolie-ville', 1280, 'مسبح منتجع جولي فيل المطل على النيل')], ll: [25.6592, 32.6178], gal: G('jolie-ville-kings-island', 5, 'غروب بين النخيل على جزيرة نيلية في الأقصر'), galcr: 'Steve F-E-Cameron (Merlin-UK) · CC BY-SA 3.0' },
    { slug: 'sonesta-st-george', c: 'stay', p: 'gems', n: 'سونستا سان جورج', s: 'فندق على كورنيش النيل قرب وسط المدينة.', d: 'فندق على كورنيش النيل بإطلالة على النهر، على مسافة قريبة من المتحف ومعبد الأقصر.', imgs: [std('stay-sonesta', 1280, 'مبنى فندق سونستا سان جورج في الأقصر')], ll: [25.6905, 32.6335], gal: G('sonesta-st-george', 5, 'كورنيش الأقصر ليلًا والنيل'), galcr: 'Marc Ryckaert، Crashsystems، Karelj · CC BY 4.0، CC BY-SA 3.0، Public domain' },
    { slug: 'villa-nile', c: 'stay', p: 'culture', n: 'فيلا نايل', s: 'بيت ضيافة بطابع محلي هادئ.', d: 'بيت ضيافة صغير بسطح يطل على الأسطح والقباب والنيل، يديره أهله ويقدّم فطورًا منزليًا.', imgs: [std('stay-villa-nile', 1280, 'إطلالة من فيلا نايل على الأسطح والقباب والنيل')], ll: [25.7218, 32.6208], gal: G('villa-nile', 5, 'بيوت بطابع محلي وقباب نوبية'), galcr: 'Warren LeMay from Chicago, IL, United States، Bernard DUPONT from FRANCE · CC0، CC BY-SA 2.0' },
    { slug: 'el-herfagya-leather', c: 'product', p: 'products', n: 'منتجات الحرفجية الجلدية', s: 'حقائب وإكسسوارات جلدية مصنوعة يدويًا بنقوش مستوحاة من التراث.', d: 'حقائب ومحافظ وإكسسوارات جلدية تُقطع وتُخاط يدويًا في ورشة الحرفجية بالأقصر، بزخارف مستوحاة من النقوش المصرية القديمة. يمكن زيارة الورشة ومشاهدة العمل.', imgs: [std('Fatma Boghdady', 1448, 'فاطمة البغدادي في ورشتها وأمامها حقائب جلدية')], ll: [25.7032, 32.6425], ent: FATMA, gal: G('el-herfagya-leather', 4, 'صناعة الجلود يدويًا ونقشها'), galcr: 'Amudena Rutkowska، Vyacheslav Kirillin · CC BY-SA 4.0' },
    { slug: 'zainab-accessories', c: 'product', p: 'products', n: 'إكسسوارات زينب', s: 'عقود وإكسسوارات يدوية بتصاميم مستوحاة من الطبيعة والتراث.', d: 'عقود وأساور وإكسسوارات تُصنع يدويًا من الخرز والخامات المحلية، بتصاميم تعكس ألوان الصعيد وتراثه.', imgs: [std('Zainab Gamal', 1461, 'زينب جمال تعرض مجموعة من العقود والإكسسوارات اليدوية')], ll: [25.7000, 32.6452], ent: ZAINAB, gal: G('zainab-accessories', 4, 'عقود وإكسسوارات يدوية ملوّنة'), galcr: 'لا روسا، Cutietuy · CC BY-SA 4.0، CC BY 4.0، CC BY-SA 3.0' },
  ].map(e => ({ ...e, city: 'luxor' }));
  const nubian2 = asw('nubian2', 'زقاق بجدران زرقاء في قرية نوبية بأسوان'), nubian1 = asw('nubian1', 'أسطح بيوت نوبية وقبابها في أسوان'), silver = asw('silver', 'حرفية نوبية تشكّل قطعة فضة في ورشتها بأسوان');
  const W = [
    { slug: 'felucca-nile-tour', c: 'tour', p: 'gems', n: 'جولة بالفلوكة في النيل', s: 'إبحار هادئ بين الجزر والصخور وقت الغروب.', d: 'تنطلق الفلوكة من الكورنيش وتدور حول جزيرة إلفنتين وجزيرة النباتات بين الصخور الجرانيتية، ويقودها نوتية من أهل الجزر. أجمل وقت لها قبل الغروب بساعة.', dur: 'ساعة إلى ساعتين', imgs: [felucca, asw('nile3', 'فلوكتان على النيل من الأعلى'), asw('nile4', 'فلوكة أمام كورنيش أسوان')], ll: [24.0889, 32.8930], gal: G('felucca-nile-tour', 6, 'فلوكات تبحر بين جزر وصخور أسوان'), galcr: 'Marc Ryckaert (MJJR)، Maris Teteris، Vyacheslav Argenberg · CC BY 3.0، CC BY 4.0' },
    { slug: 'nubian-village-experience', c: 'tour', p: 'culture', n: 'زيارة القرية النوبية', s: 'بيوت ملوّنة وضيافة نوبية على ضفة النيل في غرب سهيل.', d: 'زيارة قرية غرب سهيل بمركب، والتجوّل بين بيوتها المقبّبة الملوّنة، ثم شاي وضيافة في بيت نوبي مع أهله. يمكن إضافة عشاء نوبي منزلي.', dur: 'نصف يوم', imgs: [nubian2, nubian1], ll: [24.0510, 32.8720], gal: G('nubian-village-experience', 4, 'بيوت القرية النوبية الملوّنة على ضفة النيل'), galcr: 'Marc Ryckaert (MJJR)، Rémih، MrSnooks، Verity Cridland · CC BY 3.0، CC BY-SA 3.0، CC BY-SA 2.0، CC BY 2.0' },
    { slug: 'elephantine-island', c: 'tour', p: 'gems', n: 'استكشاف جزيرة إلفنتين', s: 'آثار ومقياس النيل وقرى نوبية على جزيرة.', d: 'جولة سيرًا على جزيرة إلفنتين بين آثار أسوان القديمة ومقياس النيل ومتحف الجزيرة، ثم قريتي سيو وكوتي النوبيتين وسط النخيل.', dur: '3 ساعات تقريبًا', imgs: [asw('elephantine2', 'أطلال جزيرة إلفنتين على ضفة النيل'), asw('elephantine', 'جزيرة إلفنتين وسط النيل مع مركب شراعي')], ll: [24.0870, 32.8869], gal: G('elephantine-island', 5, 'جزيرة إلفنتين وآثارها ومقياس النيل'), galcr: 'Marc Ryckaert، Marc Ryckaert (MJJR)، Hatem Moushir، Olaf Tausch · CC BY 3.0، CC BY-SA 4.0' },
    { slug: 'philae-temple-visit', c: 'tour', p: 'culture', n: 'زيارة معبد فيلة', s: 'معبد إيزيس على جزيرة أجيليكا.', d: 'رحلة بالمركب إلى جزيرة أجيليكا لزيارة معبد إيزيس الذي نُقل حجرًا حجرًا لإنقاذه من مياه السد. مع مرشد محلي يشرح النقوش وقصة الإنقاذ.', dur: '3 ساعات تقريبًا', imgs: [asw('philae', 'معبد فيلة على جزيرة أجيليكا'), asw('philae2', 'مدخل معبد فيلة')], ll: [24.0253, 32.8846], gal: G('philae-temple-visit', 6, 'معبد فيلة على جزيرة أجيليكا'), galcr: 'Marc Ryckaert، M.ramadan2014، Marc Ryckaert (MJJR) · CC BY 3.0، CC BY-SA 3.0' },
    { slug: 'nubian-silver-workshop', c: 'workshop', p: 'crafts', n: 'ورشة الفضة النوبية', s: 'اصنع خاتمك الفضي باسمك بالخط النوبي مع حرفيي أسوان.', d: 'ورشة عملية في محل صائغ نوبي، تتعلم فيها أساسيات تشكيل الفضة وتخرج بخاتم منقوش باسمك بالحروف النوبية.', dur: 'ساعتان تقريبًا', imgs: [silver], ll: [24.0895, 32.9000], hl: ['تعلّم أساسيات تشكيل الفضة', 'نقش اسمك بالحروف النوبية', 'تخرج بخاتمك الذي صنعته'], inc: ['الخامات والأدوات', 'الخاتم الذي تصنعه'], gal: G('nubian-silver-workshop', 4, 'حرفي يصوغ الفضة وخواتم فضية'), galcr: 'Clément Bardot، W.carter · CC BY-SA 4.0' },
    { slug: 'nile-restaurants-aswan', c: 'food', p: 'food', n: 'مطاعم على النيل', s: 'مأكولات مصرية بإطلالة على النيل وجزره.', d: 'مطاعم على الكورنيش وعلى الجزر تقدّم السمك النيلي والأطباق المصرية مع إطلالة على الصخور والمراكب.', imgs: [evening], ll: [24.0930, 32.8990], gal: G('nile-restaurants-aswan', 6, 'النيل وجزره في أسوان'), galcr: 'Marc Ryckaert (MJJR)، Marc Ryckaert · CC BY 3.0' },
    { slug: 'nubian-restaurants', c: 'food', p: 'food', n: 'مطاعم نوبية', s: 'أطباق نوبية تقليدية في بيوت وقرى على ضفة النيل.', d: 'مطاعم صغيرة في القرى النوبية تقدّم أطباقًا نوبية بالتوابل المحلية والخبز النوبي، غالبًا في أفنية البيوت.', imgs: [nubian1, nubian2], ll: [24.0525, 32.8735], gal: G('nubian-restaurants', 5, 'أطباق نوبية ومقهى نوبي'), galcr: 'Kent Wang · CC BY-SA 2.0' },
    { slug: 'local-cafes-aswan', c: 'food', p: 'food', n: 'مقاهي محلية', s: 'شاي وقهوة وجلسات هادئة في مقاهي المدينة.', d: 'مقاهي السوق والكورنيش لشاي الكركديه والقهوة ومتابعة إيقاع المدينة الهادئ.', imgs: [tea], ll: [24.0900, 32.8975], gal: G('local-cafes-aswan', 5, 'سوق أسوان ومقاهيه ليلًا'), galcr: 'Rémih، Silar، Karelj · CC BY-SA 3.0، Public domain' },
    { slug: 'home-cooked-nubian', c: 'food', p: 'food', n: 'تجارب طعام منزلية', s: 'وجبات منزلية تُعدّ وتُقدَّم في بيوت نوبية.', d: 'وجبة تُطهى في بيت نوبي وتُقدَّم لضيوف قلائل، مع شرح المكوّنات وطريقة التحضير. تُحجز مسبقًا عبر التواصل.', imgs: [nubian2], ll: [24.0505, 32.8725], gal: G('home-cooked-nubian', 4, 'سيدة تخبز الخبز البلدي في بيت نوبي'), galcr: 'Mohamed Hozyen Ahmed، Ahmed Emad Hamdy، لا روسا · CC BY-SA 4.0' },
    { slug: 'nubian-hotels', c: 'stay', p: 'culture', n: 'فنادق نوبية', s: 'إقامة بطابع نوبي في غرب سهيل.', d: 'بيوت وفنادق صغيرة في القرى النوبية بغرفها المقبّبة وألوانها الزاهية وأفنيتها المفتوحة على النيل.', imgs: [nubian2], ll: [24.0500, 32.8740], gal: G('nubian-hotels', 4, 'فنادق وبيوت نوبية ملوّنة في غرب سهيل'), galcr: 'gina monica butoi، Mgalal20، Alberto-g-rovi، Belmahdy · CC BY 3.0، CC BY-SA 4.0' },
    { slug: 'nubian-guesthouses', c: 'stay', p: 'culture', n: 'بيوت ضيافة', s: 'بيوت يديرها أهلها في القرى النوبية.', d: 'غرف بسيطة في بيوت نوبية يديرها أصحابها، مع فطور منزلي وقرب من النيل والقرية.', imgs: [nubian1], ll: [24.0520, 32.8750], gal: G('nubian-guesthouses', 5, 'بيوت ضيافة نوبية بقبابها وزخارفها'), galcr: 'Warren LeMay from Chicago, IL, United States · CC0' },
    { slug: 'nile-view-stays', c: 'stay', p: 'gems', n: 'إقامة على النيل', s: 'إقامة بإطلالة على النيل وجزيرة إلفنتين.', d: 'فنادق على الكورنيش وعلى الصخور المطلة على النيل، بإطلالات مفتوحة على إلفنتين ومراكب الفلوكة.', imgs: [asw('cataract2', 'إطلالة على النيل وجزيرة إلفنتين من ضفة أسوان'), asw('cataract', 'فنادق على صخور النيل في أسوان')], ll: [24.0830, 32.8960], gal: G('nile-view-stays', 5, 'إطلالات على النيل في أسوان'), galcr: 'Marc Ryckaert (MJJR)، Ad Meskens، David Berkowitz from New York, NY, USA · CC BY 3.0، CC BY-SA 3.0، CC BY 2.0' },
    { slug: 'island-stays', c: 'stay', p: 'gems', n: 'إقامة بين الجزر', s: 'إقامة هادئة على جزر النيل.', d: 'إقامات على جزر النيل يُوصل إليها بالمركب، وسط الحدائق والهدوء بعيدًا عن حركة المدينة.', imgs: [asw('kitchener', 'حديقة جزيرة النباتات ومراكب على شاطئها')], ll: [24.0873, 32.8790], gal: G('island-stays', 5, 'جزيرة النباتات ونخيلها في أسوان'), galcr: 'Karelj، Martin Strachoň، Pufacz، Marc Ryckaert (MJJR) · Public domain، CC BY-SA 3.0، CC BY 3.0' },
    { slug: 'el-beit-elnoby-textiles', c: 'product', p: 'products', n: 'منتجات البيت النوبي', s: 'أقمشة ومنسوجات مطرزة بأيدي سيدات نوبيات.', d: 'منسوجات وأقمشة مطرزة بزخارف نوبية تصنعها سيدات تدرّبن في البيت النوبي، وتُباع لدعم ورش التدريب في أسوان.', imgs: [std('Manal Awaga', 1448, 'منال عوض الله في البيت النوبي تعرض أقمشة مطرزة')], ll: [24.0505, 32.8730], ent: MANAL, gal: G('el-beit-elnoby-textiles', 5, 'نول ومنسوجات ومطرزات نوبية'), galcr: 'Hagar.mokhtar، Aseel zm، Ahmed Hagrasi، Joey Berzowska، आशीष भटनागर at hi.wikipedia · CC BY-SA 4.0، CC BY 2.0، Public domain' },
    { slug: 'nubian-silver-jewellery', c: 'product', p: 'crafts', n: 'مشغولات الفضة النوبية', s: 'خواتم وحلي فضية منقوشة بالحروف النوبية.', d: 'خواتم وأساور وقلائد فضية تُنقش يدويًا بالحروف والزخارف النوبية في ورش أسوان.', imgs: [silver], ll: [24.0895, 32.9000], gal: G('nubian-silver-jewellery', 5, 'أساور وحلي فضية مشغولة يدويًا'), galcr: 'Handmadejewelry، W.carter، Marsupium · CC BY-SA 3.0، CC BY-SA 4.0، CC BY 4.0' },
  ].map(e => ({ ...e, city: 'aswan' }));
  return { CAT, PIL, list: [...L, ...W] };
})();
